name: Sentiment API CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask app in background
      run: |
        python app.py &
        sleep 5  # give time to start

    - name: Test API with curl
      run: |
        curl -X POST http://127.0.0.1:5000/predict \
             -H "Content-Type: application/json" \
             -d "{\"tweet\": \"This is awesome!\"}"

    - name: Build Docker image
      run: docker build -t sentiment-api .

    # Optional: Push to Docker Hub (uncomment if credentials are set)
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker image
    #   run: docker push yourusername/sentiment-api:v1
